#' @title Quicknet
#' @description Generates an internal R network representing the miR-mRNA
#' interactions filtered through the input data using wikipathways analysis and
#' database filtering/
#' @param net network generated by Makenet function. If you have fewer than two
#' interactions the plot will not work.
#' @return A network depicting miR-mRNA interactions.
#' @export
#' @importFrom igraph V V<- E E<-
#' @importFrom graphics legend par plot
#' @usage Quicknet(net)
Quicknet <- function(net){
        V(net)$color <- ifelse(V(net)$genetype == "mRNA", "lightblue", "pink")
        E(net)$width <- E(net)$Databases
        ii <- cut(E(net)$Correlation,
        breaks = seq(min(E(net)$Correlation),
        max(E(net)$Correlation),
        len = length(E(net)$Correlation)),
        include.lowest = TRUE)
        colors <- colorRampPalette(c("red", "grey",
        "green"))(length(E(net)$Correlation))[ii]
        legcol <- colorRampPalette(c("red", "grey", "green"))(3)
        E(net)$edge.color <- colors
        E(net)$edge.color
        E(net)$Correlation
        par(mar=c(1, 1, 1, 1))
        plot(net, edge.arrow.size=.4,vertex.label=V(net)$genes,
        vertex.shape = "circle", vertex.size = 20, vertex.label.cex = 0.8,
        vertex.label.dist = 0, frame = TRUE, main = "miR-mRNA interactions",
        edge.curved = 0.5, vertex.frame.color = "white", edge.color = colors)
        legend(x = -2.4, y = -0.4, legend = round(c(min(E(net)$Correlation),
        median(E(net)$Correlation), max(E(net)$Correlation)), 2),
        fill = legcol, border = NA, y.intersp = 0.7, cex = 0.8,
        text.font = 0.2, title = "Correlations")
        legend(x=-2.4, y=-0.8, c("microRNA","mRNA"), pch=21, col="#777777",
        pt.bg= c("pink", "lightblue"), pt.cex=2, cex=1, bty="n", ncol=1)
}
