#' @title Quicknet
#' @description Generates an internal R network representing the miR-mRNA
#' interactions filtered through the input data using wikipathways analysis and
#' database filtering/
#' @param net network generated by Makenet function. If you have fewer than two
#' interactions the plot will not work.
#' @return A network depicting miR-mRNA interactions.
#' @export
#' @importFrom igraph V V<- E E<-
#' @importFrom graphics legend par plot
#' @usage Quicknet(net)
#' @examples 
#' library(igraph)
#' library(biomaRt)
#' library(MultiAssayExperiment)
#' 
#' Filt_df <- data.frame(row.names = c("mmu-miR-320-3p:Acss1",
#'                                      "mmu-miR-27a-3p:Odc1"),
#'                       avecor = c(-0.9191653, 0.7826041),
#'                       miR = c("mmu-miR-320-3p", "mmu-miR-27a-3p"),
#'                       mRNA = c("Acss1", "Acss1"),
#'                       miR_Entrez = c(NA, NA),
#'                       mRNA_Entrez = c(68738, 18263),
#'                       TargetScan = c(1, 0),
#'                       miRDB = c(0, 0),
#'                       Predicted_Interactions = c(1, 0),
#'                       miRTarBase = c(0, 1),
#'                       Pred_Fun = c(1, 1))
#'MAE <- MultiAssayExperiment()
#'MAE <- MakeNet(MAE, Filt_df)
#'Q <- Quicknet(metadata(MAE)[[1]])
Quicknet <- function(net){
    
    if(missing(net)) stop('Run MakeNet on filtered miR-mRNA interactions df.')
    
    # Set network colours and features
    V(net)$color <- ifelse(V(net)$genetype == "mRNA", "lightblue", "pink")
    E(net)$width <- E(net)$Databases
    ii <- cut(E(net)$Correlation,
    breaks = seq(min(E(net)$Correlation),
                 max(E(net)$Correlation),
                 len = length(E(net)$Correlation)),
                 include.lowest = TRUE)
                 colors <- colorRampPalette(c("red", "grey",
                                            "green"))(
                                             length(E(net)$Correlation))[ii]
                 legcol <- colorRampPalette(c("red", "grey", "green"))(3)
    
    E(net)$edge.color <- colors

    par(mar=c(1, 1, 1, 1))
    
    plot(net, edge.arrow.size=.4,
         vertex.label=V(net)$genes,
         vertex.shape = "circle", 
         vertex.size = 20,
         vertex.label.cex = 0.8,
         vertex.label.dist = 0,
         frame = TRUE,
         main = "miR-mRNA interactions", 
         edge.curved = 0.5,
         vertex.frame.color = "white", 
         edge.color = colors)
    # Make legend
    legend(x = -2.4, y = -0.4, 
           legend = round(c(min(E(net)$Correlation),
                            median(E(net)$Correlation),
                            max(E(net)$Correlation)), 2),
           fill = legcol, 
           border = NA,
           y.intersp = 0.7,
           cex = 0.8,
           text.font = 0.2,
           title = "Corr")
    # Colour legend
    legend(x=-2.4, y=-0.8,
           c("microRNA","mRNA"),
           pch=21, 
           col="#777777",
    pt.bg= c("pink", "lightblue"),
            pt.cex=2,
            cex=1,
            bty="n", 
            ncol=1)
}
